package Views;

import Clases.ClsCandidate;
import Clases.ClsMessage;
import Controllers.CtlCandidate;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danie
 */
public class CandidateView extends javax.swing.JFrame {

    // Declarar variable / Crear un objeto
    JFrame ObjMainMenu;
    
    // Controlador
    CtlCandidate candidateControler;
    
    // Resultados
    LinkedList<ClsCandidate> candidateListObj = new LinkedList<>();
    
    // Manipular
    LinkedList<ClsCandidate> candidateGetList;

    /**
     * Creates new form CandidateView
     */
    public CandidateView(JFrame mainMenu) {
        initComponents();
        // Instanciar
        this.ObjMainMenu = mainMenu;
        this.candidateControler = new CtlCandidate();
        
        this.jButtonCandidateNew.setVisible(false);
        this.jButtonCandidateUpdate.setVisible(false);
        
        // Llamar método para obtención datos
        this.GetJTb_candidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        candidateForm = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoCedula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoCorreo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        campoDescripcion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        campoMensajeCampania = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        campoPropuestas = new javax.swing.JTextField();
        comboCiudadOrigen = new javax.swing.JComboBox<>();
        comboPartido = new javax.swing.JComboBox<>();
        jButtonCandidateUpdate = new javax.swing.JButton();
        jButtonCandidateAdd = new javax.swing.JButton();
        jButtonCandidateNew = new javax.swing.JButton();
        jPanel5CandidatePaneList = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane = new javax.swing.JScrollPane();
        candidateTable = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jButtonCandidateDelete = new javax.swing.JButton();
        jButtonCandidateEdit = new javax.swing.JButton();
        jButtonBackMainView = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(408, 308));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Gestor Candidato");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        candidateForm.setBackground(new java.awt.Color(255, 255, 255));
        candidateForm.setForeground(new java.awt.Color(0, 102, 255));
        candidateForm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        candidateForm.setFocusTraversalPolicyProvider(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setFocusable(false);

        jLabel4.setBackground(new java.awt.Color(0, 102, 255));
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Nombre:");

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Número documento");

        campoNombre.setBackground(new java.awt.Color(204, 204, 204));
        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        campoCedula.setBackground(new java.awt.Color(204, 204, 204));
        campoCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCedulaActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Teléfono");

        campoTelefono.setBackground(new java.awt.Color(204, 204, 204));
        campoTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTelefonoActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Correo");

        campoCorreo.setBackground(new java.awt.Color(204, 204, 204));
        campoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCorreoActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Partido");

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Ciudad");

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Descripción");

        campoDescripcion.setBackground(new java.awt.Color(204, 204, 204));
        campoDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDescripcionActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Mensaje");

        campoMensajeCampania.setBackground(new java.awt.Color(204, 204, 204));
        campoMensajeCampania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoMensajeCampaniaActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Propuestas");

        campoPropuestas.setBackground(new java.awt.Color(204, 204, 204));
        campoPropuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPropuestasActionPerformed(evt);
            }
        });

        comboCiudadOrigen.setBackground(new java.awt.Color(153, 153, 153));
        comboCiudadOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "--", "Armenia", "Bogotá", "Manizales", "Cali", "Medellín" }));
        comboCiudadOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCiudadOrigenActionPerformed(evt);
            }
        });

        comboPartido.setBackground(new java.awt.Color(153, 153, 153));
        comboPartido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "--", "Demócrata", "De la U", "Liberal", "Pacto histórico" }));
        comboPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPartidoActionPerformed(evt);
            }
        });

        jButtonCandidateUpdate.setBackground(new java.awt.Color(0, 204, 51));
        jButtonCandidateUpdate.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButtonCandidateUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCandidateUpdate.setText("Actualizar");
        jButtonCandidateUpdate.setBorderPainted(false);
        jButtonCandidateUpdate.setFocusPainted(false);
        jButtonCandidateUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCandidateUpdateActionPerformed(evt);
            }
        });

        jButtonCandidateAdd.setBackground(new java.awt.Color(204, 204, 204));
        jButtonCandidateAdd.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButtonCandidateAdd.setForeground(new java.awt.Color(0, 102, 255));
        jButtonCandidateAdd.setText("Agregar");
        jButtonCandidateAdd.setBorderPainted(false);
        jButtonCandidateAdd.setFocusPainted(false);
        jButtonCandidateAdd.setFocusable(false);
        jButtonCandidateAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCandidateAddActionPerformed(evt);
            }
        });

        jButtonCandidateNew.setBackground(new java.awt.Color(0, 102, 204));
        jButtonCandidateNew.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButtonCandidateNew.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCandidateNew.setText("Nuevo");
        jButtonCandidateNew.setBorderPainted(false);
        jButtonCandidateNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCandidateNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonCandidateAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCandidateNew)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCandidateUpdate)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(campoPropuestas)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(campoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(campoNombre)
                                .addContainerGap())))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(comboCiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(campoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoMensajeCampania)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel10)
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel11)
                                        .addGap(61, 61, 61))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(comboPartido, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addGap(12, 12, 12))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoMensajeCampania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoPropuestas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCandidateAdd)
                    .addComponent(jButtonCandidateUpdate)
                    .addComponent(jButtonCandidateNew))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        candidateForm.addTab("Formulario", jPanel3);

        jPanel5CandidatePaneList.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 204));

        candidateTable.setBackground(new java.awt.Color(204, 204, 204));
        candidateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cédula", "Nombre", "Teléfono", "Correo", "Partido", "Ciudad", "Descripción", "Mensaje", "Propuestas"
            }
        ));
        candidateTable.setFocusable(false);
        candidateTable.setOpaque(false);
        candidateTable.setPreferredSize(new java.awt.Dimension(375, 300));
        candidateTable.setShowGrid(true);
        candidateTable.setShowHorizontalLines(false);
        candidateTable.setShowVerticalLines(false);
        jScrollPane.setViewportView(candidateTable);

        jScrollPane2.setViewportView(jScrollPane);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Puede eliminar y actualizar registros");

        jButtonCandidateDelete.setBackground(new java.awt.Color(255, 204, 0));
        jButtonCandidateDelete.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButtonCandidateDelete.setForeground(new java.awt.Color(255, 0, 0));
        jButtonCandidateDelete.setText("Eliminar");
        jButtonCandidateDelete.setBorderPainted(false);
        jButtonCandidateDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCandidateDeleteActionPerformed(evt);
            }
        });

        jButtonCandidateEdit.setBackground(new java.awt.Color(0, 204, 51));
        jButtonCandidateEdit.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButtonCandidateEdit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCandidateEdit.setText("Editar");
        jButtonCandidateEdit.setBorderPainted(false);
        jButtonCandidateEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCandidateEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5CandidatePaneListLayout = new javax.swing.GroupLayout(jPanel5CandidatePaneList);
        jPanel5CandidatePaneList.setLayout(jPanel5CandidatePaneListLayout);
        jPanel5CandidatePaneListLayout.setHorizontalGroup(
            jPanel5CandidatePaneListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5CandidatePaneListLayout.createSequentialGroup()
                .addGroup(jPanel5CandidatePaneListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5CandidatePaneListLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5CandidatePaneListLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel13)
                        .addGap(0, 48, Short.MAX_VALUE))
                    .addGroup(jPanel5CandidatePaneListLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonCandidateDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCandidateEdit)))
                .addContainerGap())
        );
        jPanel5CandidatePaneListLayout.setVerticalGroup(
            jPanel5CandidatePaneListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5CandidatePaneListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5CandidatePaneListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCandidateDelete)
                    .addComponent(jButtonCandidateEdit))
                .addGap(69, 69, 69))
        );

        candidateForm.addTab("Lista", jPanel5CandidatePaneList);

        jButtonBackMainView.setBackground(new java.awt.Color(255, 204, 0));
        jButtonBackMainView.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButtonBackMainView.setForeground(new java.awt.Color(102, 51, 0));
        jButtonBackMainView.setText("Regresar");
        jButtonBackMainView.setBorderPainted(false);
        jButtonBackMainView.setFocusPainted(false);
        jButtonBackMainView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackMainViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonBackMainView)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(candidateForm, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(candidateForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButtonBackMainView)
                .addGap(19, 19, 19))
        );

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Versión 1.0");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Espacio para agregar candidato");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCandidateAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCandidateAddActionPerformed
        // BUTTON: ADD

        // Exepciones
        /**try {*/

            // Declarar variable local - Referimos variable de la clase ClsCandidate
            String documentNumber = this.campoCedula.getText();
            String name = this.campoNombre.getText();
            long phone = Long.parseLong(this.campoTelefono.getText());
            String mail = this.campoCorreo.getText();
            String party = this.comboPartido.getSelectedItem().toString();
            String hometown = this.comboCiudadOrigen.getSelectedItem().toString();
            String description = this.campoDescripcion.getText();
            String campaign_message = this.campoMensajeCampania.getText();
            String proposals = this.campoPropuestas.getText();

            /**
            // Lógica / Condicionar
            if (documentNumber.equals("") || name.equals("") || description.equals("") || campaign_message.equals("")) {

                JOptionPane.showMessageDialog(this, "Complete el campo");

            } else {*/

                // Crear objeto de tipo ClsCandidate / Enviar parámetros
            ClsCandidate candidateObj = new ClsCandidate(documentNumber, name, phone, mail, party, hometown, description, campaign_message, proposals);

                // Llamar controlador / respuesta es para si se puede o no agregar
                //boolean respuesta = this.candidateControler.candidateAdd(candidate);
                //this.candidateControler.candidateAdd(candidate);
                // Almacenar en lista
                //candidateListObj.add(candidate);
                //this.FillJTable();
                
                // Agregamos
                ClsMessage message = this.candidateControler.candidateAdd(candidateObj);
                
                if (message.getType().equals(ClsMessage.OK)) {
                    CandidatesGetting();
                }
                
                JOptionPane.showMessageDialog(rootPane, message.getText());

                // Generar alerta
                /**JOptionPane.showMessageDialog(this, "El perfil del candidato: " + name + " " + "ha sido ingresado con éxito.");

            }

        } catch (Exception e) {

            // Generar alerta
            JOptionPane.showMessageDialog(this, "Por favor, inserte números.");
        }*/


    }//GEN-LAST:event_jButtonCandidateAddActionPerformed

    // Obtener candidatos
    public void CandidatesGetting() {
        
        this.candidateListObj = this.candidateControler.GetJTb_candidate();
        this.UpdateJtb_candidate(candidateListObj);

    }
    
    // 1 M - Crear función que llama e indica al controlador que el modelo entregue datos y asigna a lista
    public void GetJTb_candidate(){
        
        //LinkedList<ClsCandidate> candidateGetList = this.candidateControler.GetJTb_candidate();
        this.candidateGetList = this.candidateControler.GetJTb_candidate();
        // Actualiza
        this.UpdateJtb_candidate(candidateGetList);
        
    }
    
    // Método / Función actualizar tabla
    public void UpdateJtb_candidate(LinkedList<ClsCandidate> updateCandidates){
        
        // Importamos para llenar tabla
        DefaultTableModel candidateModel = (DefaultTableModel) this.candidateTable.getModel();
        candidateModel.setRowCount(0);
        
        for (ClsCandidate updateCandidate : updateCandidates) {
            
            Object[] candidateRow = {updateCandidate.getDocumentNumber(), updateCandidate.getName(), updateCandidate.getPhone(), updateCandidate.getMail(), updateCandidate.getParty(), updateCandidate.getHometown(), updateCandidate.getDescription(), updateCandidate.getCampaign_message(), updateCandidate.getProposals()};
            
            candidateModel.addRow(candidateRow);
            
            
        }
         
    }
    
    // Prueba
    // Método privado para poner en lista de forma interna
    /**private void FillJTable() {

        // Importamos para llenar tabla
        DefaultTableModel candidateModel = (DefaultTableModel) candidateTable.getModel();
        //DefaultTableModel candidateModel = new DefaultTableModel();
        //candidateTable.setModel(candidateModel);

        Object[] candidateRow = new Object[9];

        candidateRow[0] = this.campoCedula.getText();
        candidateRow[1] = this.campoNombre.getText();
        candidateRow[2] = Long.parseLong(this.campoTelefono.getText());
        candidateRow[3] = this.campoCorreo.getText();
        candidateRow[4] = this.comboPartido.getSelectedItem().toString();
        candidateRow[5] = this.comboCiudadOrigen.getSelectedItem().toString();
        candidateRow[6] = this.campoDescripcion.getText();
        candidateRow[7] = this.campoMensajeCampania.getText();
        candidateRow[8] = this.campoPropuestas.getText();

        candidateModel.addRow(candidateRow);

        candidateTable.setModel(candidateModel);

    }
    */


    private void jButtonCandidateUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCandidateUpdateActionPerformed
        // BUTTON: UPDATE
        
        String documentNumber = this.campoCedula.getText();
        String name = this.campoNombre.getText();
        long phone = Long.parseLong(this.campoTelefono.getText());
        String mail = this.campoCorreo.getText();
        String party = this.comboPartido.getSelectedItem().toString();
        String hometown = this.comboCiudadOrigen.getSelectedItem().toString();
        String description = this.campoDescripcion.getText();
        String campaign_message = this.campoMensajeCampania.getText();
        String proposals = this.campoPropuestas.getText();

        ClsCandidate candidateUpdate = new ClsCandidate(documentNumber, name, phone, mail, party, hometown, description, campaign_message, proposals);
        
        ClsMessage message = this.candidateControler.CandidateUpdate(candidateUpdate);

        if (message.getType().equals(ClsMessage.OK)) {
            GetJTb_candidate();
        }

        JOptionPane.showMessageDialog(rootPane, message.getText());
    }//GEN-LAST:event_jButtonCandidateUpdateActionPerformed

    private void jButtonBackMainViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackMainViewActionPerformed
        // BUTTON: BACK
        this.setVisible(false);
        this.ObjMainMenu.setVisible(true);
    }//GEN-LAST:event_jButtonBackMainViewActionPerformed

    private void campoDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDescripcionActionPerformed

    private void campoCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCedulaActionPerformed

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void comboCiudadOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCiudadOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCiudadOrigenActionPerformed

    private void comboPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPartidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPartidoActionPerformed

    private void campoPropuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPropuestasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPropuestasActionPerformed

    private void campoMensajeCampaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMensajeCampaniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMensajeCampaniaActionPerformed

    private void campoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelefonoActionPerformed

    private void campoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCorreoActionPerformed

    private void jButtonCandidateDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCandidateDeleteActionPerformed
        // BUTTON: DELETE
        int candidateColumn = 0;
        int candidateRow = this.candidateTable.getSelectedRow();
        String candidateId = this.candidateTable.getValueAt(candidateRow, candidateColumn).toString();
        
        ClsMessage message = this.candidateControler.candidateDelete(candidateId);
        
        if (message.getType().equals(ClsMessage.OK)){
            
            CandidatesGetting();
            
        }
        JOptionPane.showMessageDialog(rootPane, message.getText());
    }//GEN-LAST:event_jButtonCandidateDeleteActionPerformed

    private void jButtonCandidateEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCandidateEditActionPerformed
        // BUTTON: EDIT 
        this.candidateForm.setSelectedIndex(0);
        
        int candidateColumn = 0;
        int candidateRow = this.candidateTable.getSelectedRow();
        String candidateId = this.candidateTable.getValueAt(candidateRow, candidateColumn).toString();
        
        ClsCandidate candidateSearchEdit = this.CandidateSearch(candidateId);
        
        if (candidateSearchEdit != null){
            
            this.campoCedula.setEnabled(false);
            this.jButtonCandidateAdd.setVisible(false);
            
            this.jButtonCandidateUpdate.setVisible(true);
            this.jButtonCandidateNew.setVisible(true);
            
            this.campoCedula.setText(candidateSearchEdit.getDocumentNumber());
            this.campoNombre.setText(candidateSearchEdit.getName());
            this.campoTelefono.setText(String.valueOf(candidateSearchEdit.getPhone()));
            this.campoCorreo.setText(candidateSearchEdit.getMail());
            this.comboCiudadOrigen.setSelectedItem(candidateSearchEdit.getHometown());
            this.comboPartido.setSelectedItem(candidateSearchEdit.getParty());
            this.campoDescripcion.setText(candidateSearchEdit.getDescription());
            this.campoMensajeCampania.setText(candidateSearchEdit.getCampaign_message());
            this.campoPropuestas.setText(candidateSearchEdit.getProposals());
            
        }
        
        
        
    }//GEN-LAST:event_jButtonCandidateEditActionPerformed

    private void jButtonCandidateNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCandidateNewActionPerformed
        // BUTTON: NEW
        this.jButtonCandidateAdd.setVisible(true);
        this.jButtonCandidateUpdate.setVisible(false);
        this.jButtonCandidateNew.setVisible(false);
        
        this.campoCedula.setEnabled(true);
        
        this.campoCedula.setText("");
        this.campoNombre.setText("");
        this.campoTelefono.setText("");
        this.campoCorreo.setText("");
        this.comboCiudadOrigen.setSelectedItem("");
        this.comboPartido.setSelectedItem("");
        this.campoDescripcion.setText("");
        this.campoMensajeCampania.setText("");
        this.campoPropuestas.setText("");
        
        
        
    }//GEN-LAST:event_jButtonCandidateNewActionPerformed

    public ClsCandidate CandidateSearch(String candidateId){
        
        for (ClsCandidate candidateSearch : this.candidateGetList) {
            
            if(candidateId.equals(candidateSearch.getDocumentNumber())){
                
                return candidateSearch;
                
            }
            
        }
        
        return null;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CandidateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CandidateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CandidateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CandidateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CandidateView(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoCedula;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JTextField campoDescripcion;
    private javax.swing.JTextField campoMensajeCampania;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoPropuestas;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JTabbedPane candidateForm;
    private javax.swing.JTable candidateTable;
    private javax.swing.JComboBox<String> comboCiudadOrigen;
    private javax.swing.JComboBox<String> comboPartido;
    private javax.swing.JButton jButtonBackMainView;
    private javax.swing.JButton jButtonCandidateAdd;
    private javax.swing.JButton jButtonCandidateDelete;
    private javax.swing.JButton jButtonCandidateEdit;
    private javax.swing.JButton jButtonCandidateNew;
    private javax.swing.JButton jButtonCandidateUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5CandidatePaneList;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
