package Views;

import Clases.ClsMessage;
import Clases.ClsVoter;
import Controllers.CtlVoter;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danie
 */
public class VoterView extends javax.swing.JFrame {
    
    // Declarar variable / Crear un objeto
    JFrame ObjMainMenu;
    
    // Controlador
    CtlVoter voterControler;
    
    // Manipular
    LinkedList<ClsVoter> voterGetList;
    
    // Resultados
    LinkedList<ClsVoter> voterListObj = new LinkedList<>();

    /**
     * Creates new form VoterView
     */
    public VoterView(JFrame mainMenu) {
        initComponents();
        
        // Instanciar
        this.ObjMainMenu = mainMenu;
        
        this.voterControler = new CtlVoter();
        
        this.jButtonVoterNew.setVisible(false);
        this.jButtonVoterUpdate.setVisible(false);
        
        // Llamar método para obtención datos
        this.GetJTb_voter();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        voterForm = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        comboTipoDocumento = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoTelefono = new javax.swing.JTextField();
        campoCedula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoCorreo = new javax.swing.JTextField();
        jButtonVoterAdd = new javax.swing.JButton();
        jButtonVoterUpdate = new javax.swing.JButton();
        jButtonVoterNew = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        campoDireccion = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        voterTable = new javax.swing.JTable();
        jButtonVoterEdit = new javax.swing.JButton();
        jButtonVoterDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(409, 534));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Versión 1.0");
        jLabel1.setFocusable(false);

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 51, 0));
        jButton1.setText("Regresar");
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Registro Votante");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Espacio para agregar votante");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        comboTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "--", "Cédula de ciudadanía", "Tarjeta de identidad" }));
        comboTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoDocumentoActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Número de documento:");

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Tipo de documento:");

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Nombre:");

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Teléfono:");

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Correo electrónico:");

        jButtonVoterAdd.setBackground(new java.awt.Color(204, 204, 255));
        jButtonVoterAdd.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButtonVoterAdd.setForeground(new java.awt.Color(0, 102, 255));
        jButtonVoterAdd.setText("Agregar");
        jButtonVoterAdd.setBorderPainted(false);
        jButtonVoterAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoterAddActionPerformed(evt);
            }
        });

        jButtonVoterUpdate.setBackground(new java.awt.Color(0, 204, 51));
        jButtonVoterUpdate.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButtonVoterUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVoterUpdate.setText("Actualizar");
        jButtonVoterUpdate.setBorderPainted(false);
        jButtonVoterUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoterUpdateActionPerformed(evt);
            }
        });

        jButtonVoterNew.setBackground(new java.awt.Color(0, 102, 255));
        jButtonVoterNew.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButtonVoterNew.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVoterNew.setText("Nuevo");
        jButtonVoterNew.setBorderPainted(false);
        jButtonVoterNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoterNewActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Dirección:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonVoterAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonVoterNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonVoterUpdate))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(comboTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(campoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                .addComponent(campoCorreo))
                            .addComponent(jLabel8))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoTelefono)
                                    .addComponent(campoCedula)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel7))
                                        .addGap(0, 21, Short.MAX_VALUE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(campoDireccion)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVoterAdd)
                    .addComponent(jButtonVoterUpdate)
                    .addComponent(jButtonVoterNew))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        voterForm.addTab("Formulario", jPanel3);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        voterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cédula", "Nombre", "Teléfono", "Correo electrónico", "Dirección", "Tipo documento"
            }
        ));
        jScrollPane1.setViewportView(voterTable);

        jButtonVoterEdit.setBackground(new java.awt.Color(0, 204, 51));
        jButtonVoterEdit.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jButtonVoterEdit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVoterEdit.setText("Editar");
        jButtonVoterEdit.setBorderPainted(false);
        jButtonVoterEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoterEditActionPerformed(evt);
            }
        });

        jButtonVoterDelete.setBackground(new java.awt.Color(255, 204, 0));
        jButtonVoterDelete.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButtonVoterDelete.setForeground(new java.awt.Color(255, 0, 0));
        jButtonVoterDelete.setText("Eliminar");
        jButtonVoterDelete.setBorderPainted(false);
        jButtonVoterDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoterDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonVoterDelete)
                        .addGap(162, 162, 162)
                        .addComponent(jButtonVoterEdit))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVoterEdit)
                    .addComponent(jButtonVoterDelete))
                .addGap(26, 26, 26))
        );

        voterForm.addTab("Lista", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(voterForm, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voterForm)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addComponent(jLabel1))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.ObjMainMenu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoDocumentoActionPerformed

    private void jButtonVoterAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoterAddActionPerformed
        // BUTTON: ADD
        
        String documentNumber = this.campoCedula.getText();
        String name = this.campoNombre.getText();
        long phone = Long.parseLong(this.campoTelefono.getText());
        String mail = this.campoCorreo.getText();
        String address = this.campoDireccion.getText();
        String type_document = this.comboTipoDocumento.getSelectedItem().toString();
        
        ClsVoter voterObj = new ClsVoter(documentNumber, name, phone, mail, address, type_document);
        
        ClsMessage message = this.voterControler.voterAdd(voterObj);
        
        if (message.getType().equals(ClsMessage.OK)) {
                    VotersGetting();
                }
        
        JOptionPane.showMessageDialog(rootPane, message.getText());
    }//GEN-LAST:event_jButtonVoterAddActionPerformed

    /**
    // Obtener votantes
    public void VotersGetting() {
        
        this.voterListObj = this.voterControler.GetJTb_voter();
        this.UpdateJtb_voter(voterListObj);

    }
    */
    
    public void VotersGetting() {
        
        this.voterListObj = this.voterControler.GetJTb_voter();
        this.UpdateJtb_voter(voterListObj);

    }
    
    // 1 M - Crear función que llama e indica al controlador que el modelo entregue datos y asigna a lista / Obtener votantes
    public void GetJTb_voter(){
        
        //LinkedList<ClsCandidate> candidateGetList = this.candidateControler.GetJTb_candidate();
        this.voterGetList = this.voterControler.GetJTb_voter();
        // Actualiza
        this.UpdateJtb_voter(voterGetList);
        
    }
    
    // Método / Función actualizar tabla
    public void UpdateJtb_voter(LinkedList<ClsVoter> updateVoters){
        
        // Importamos para llenar tabla
        DefaultTableModel voterModel = (DefaultTableModel) this.voterTable.getModel();
        voterModel.setRowCount(0);
        
        for (ClsVoter updateVoter : updateVoters) {
            
            Object[] voterRow = {updateVoter.getDocumentNumber(), updateVoter.getName(), updateVoter.getPhone(), updateVoter.getMail(), updateVoter.getAddress(), updateVoter.getType_document()};
            
            voterModel.addRow(voterRow);
            
            
        }
         
    }
    
    
    
    private void jButtonVoterEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoterEditActionPerformed
        // BUTTON: EDIT 
        this.voterForm.setSelectedIndex(0);
        
        int voterColumn = 0;
        int voterRow = this.voterTable.getSelectedRow();
        String voterId = this.voterTable.getValueAt(voterRow, voterColumn).toString();
        
        ClsVoter voterSearchEdit = this.VoterSearch(voterId);
        
        if (voterSearchEdit != null){
            
            this.campoCedula.setEnabled(false);
            this.jButtonVoterAdd.setVisible(false);
            
            this.jButtonVoterUpdate.setVisible(true);
            this.jButtonVoterNew.setVisible(true);
            
            this.campoCedula.setText(voterSearchEdit.getDocumentNumber());
            this.campoNombre.setText(voterSearchEdit.getName());
            this.campoTelefono.setText(String.valueOf(voterSearchEdit.getPhone()));
            this.campoCorreo.setText(voterSearchEdit.getMail());
            this.comboTipoDocumento.setSelectedItem(voterSearchEdit.getType_document());
            
        }
        
    }//GEN-LAST:event_jButtonVoterEditActionPerformed

    private void jButtonVoterDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoterDeleteActionPerformed
        // BUTTON: DELETE
        int voterColumn = 0;
        int voterRow = this.voterTable.getSelectedRow();
        String voterId = this.voterTable.getValueAt(voterRow, voterColumn).toString();
        
        ClsMessage message = this.voterControler.voterDelete(voterId);
        
        if (message.getType().equals(ClsMessage.OK)){
            
            VotersGetting();
            
        }
        JOptionPane.showMessageDialog(rootPane, message.getText());
    
        
        
    }//GEN-LAST:event_jButtonVoterDeleteActionPerformed

    private void jButtonVoterNew(){
        this.jButtonVoterNew.setVisible(true);
    }
    
    private void jButtonVoterNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoterNewActionPerformed
        // BUTTON: NEW
        this.jButtonVoterAdd.setVisible(true);
        this.jButtonVoterUpdate.setVisible(false);
        this.jButtonVoterNew.setVisible(false);
        
        this.campoCedula.setEnabled(true);
        
        this.campoCedula.setText("");
        this.campoNombre.setText("");
        this.campoTelefono.setText("");
        this.campoCorreo.setText("");
        this.campoDireccion.setText("");
        this.comboTipoDocumento.setSelectedItem(null);
        
    }//GEN-LAST:event_jButtonVoterNewActionPerformed

    private void jButtonVoterUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoterUpdateActionPerformed
        // BUTTON: UPDATE
        
        String documentNumber = this.campoCedula.getText();
        String name = this.campoNombre.getText();
        long phone = Long.parseLong(this.campoTelefono.getText());
        String mail = this.campoCorreo.getText();
        String address = this.campoDireccion.getText();
        String type_document = this.comboTipoDocumento.getSelectedItem().toString();

        ClsVoter voterUpdate = new ClsVoter(documentNumber, name, phone, mail, address, type_document);
        
        ClsMessage message = this.voterControler.VoterUpdate(voterUpdate);

        if (message.getType().equals(ClsMessage.OK)) {
            GetJTb_voter();
        }

        JOptionPane.showMessageDialog(rootPane, message.getText());
    }//GEN-LAST:event_jButtonVoterUpdateActionPerformed

    public ClsVoter VoterSearch(String voterId){
        
        for (ClsVoter voterSearch : this.voterGetList) {
            
            if(voterId.equals(voterSearch.getDocumentNumber())){
                
                return voterSearch;
                
            }
            
        }
        
        return null;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VoterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VoterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VoterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VoterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VoterView(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoCedula;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JTextField campoDireccion;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JComboBox<String> comboTipoDocumento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonVoterAdd;
    private javax.swing.JButton jButtonVoterDelete;
    private javax.swing.JButton jButtonVoterEdit;
    private javax.swing.JButton jButtonVoterNew;
    private javax.swing.JButton jButtonVoterUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane voterForm;
    private javax.swing.JTable voterTable;
    // End of variables declaration//GEN-END:variables
}
